/****** Script for selecting all games played with Caro-Kahn B10-B19 opening  ******/
SELECT WHITE, COUNT(ECO) AS COUNT FROM CHESSDB WHERE ECO = '[ECO "B10"]'
OR ECO = '[ECO "B11"]'
OR ECO = '[ECO "B12"]'
OR ECO = '[ECO "B13"]'
OR ECO = '[ECO "B14"]'
OR ECO = '[ECO "B15"]'
OR ECO = '[ECO "B16"]'
OR ECO = '[ECO "B17"]'
OR ECO = '[ECO "B18"]'
OR ECO = '[ECO "B19"]' 
GROUP BY WHITE
HAVING WHITE = '[White "Alekhine, A. (wh)"]'
OR WHITE = '[White "Botvinnik, M. (wh)"]'
OR WHITE = '[White "Capablanca, J. (wh)"]'
OR WHITE = '[White "Fischer, R. (wh)"]'
OR WHITE = '[White "Karpov, A. (wh)"]'
OR WHITE = '[White "Kasparov, G. (wh)"]'
OR WHITE = '[White "Kramnik, V. (wh)"]'
OR WHITE = '[White "Lasker, E. (wh)"]'
OR WHITE = '[White "Petrosian, T. (wh)"]'
OR WHITE = '[White "Tal, M. (wh)"]'

/****** Script for selecting all games played with Caro-Kahn B10-B19 opening  ******/
SELECT BLACK, COUNT(ECO) AS COUNT FROM CHESSDB WHERE ECO = '[ECO "B10"]'
OR ECO = '[ECO "B11"]'
OR ECO = '[ECO "B12"]'
OR ECO = '[ECO "B13"]'
OR ECO = '[ECO "B14"]'
OR ECO = '[ECO "B15"]'
OR ECO = '[ECO "B16"]'
OR ECO = '[ECO "B17"]'
OR ECO = '[ECO "B18"]'
OR ECO = '[ECO "B19"]' 
GROUP BY BLACK
HAVING BLACK = '[Black "Alekhine, A. (bl)"]'
OR BLACK = '[Black "Botvinnik, M. (bl)"]'
OR BLACK = '[Black "Capablanca, J. (bl)"]'
OR BLACK = '[Black "Fischer, R. (bl)"]'
OR BLACK = '[Black "Karpov, A. (bl)"]'
OR BLACK = '[Black "Kasparov, G. (bl)"]'
OR BLACK = '[Black "Kramnik, V. (bl)"]'
OR BLACK = '[Black "Lasker, E. (bl)"]'
OR BLACK = '[Black "Petrosian, T. (bl)"]'
OR BLACK = '[Black "Tal, M. (bl)"]'

SELECT WHITE, COUNT(WHITE) AS COUNT FROM CHESSDB 
GROUP BY WHITE
HAVING WHITE = '[White "Alekhine, A. (wh)"]'
OR WHITE = '[White "Botvinnik, M. (wh)"]'
OR WHITE = '[White "Capablanca, J. (wh)"]'
OR WHITE = '[White "Fischer, R. (wh)"]'
OR WHITE = '[White "Karpov, A. (wh)"]'
OR WHITE = '[White "Kasparov, G. (wh)"]'
OR WHITE = '[White "Kramnik, V. (wh)"]'
OR WHITE = '[White "Lasker, E. (wh)"]'
OR WHITE = '[White "Petrosian, T. (wh)"]'
OR WHITE = '[White "Tal, M. (wh)"]'

SELECT BLACK, COUNT(BLACK) AS COUNT FROM CHESSDB
GROUP BY BLACK
HAVING BLACK = '[Black "Alekhine, A. (bl)"]'
OR BLACK = '[Black "Botvinnik, M. (bl)"]'
OR BLACK = '[Black "Capablanca, J. (bl)"]'
OR BLACK = '[Black "Fischer, R. (bl)"]'
OR BLACK = '[Black "Karpov, A. (bl)"]'
OR BLACK = '[Black "Kasparov, G. (bl)"]'
OR BLACK = '[Black "Kramnik, V. (bl)"]'
OR BLACK = '[Black "Lasker, E. (bl)"]'
OR BLACK = '[Black "Petrosian, T. (bl)"]'
OR BLACK = '[Black "Tal, M. (bl)"]'